### ISSUE TITLE
一键下载的百度云失效了

### ISSUE THREAD

**Issue by CanisYue** [lmxdawn/vue-admin-html-java#1]

**Comment by lmxdawn** [comment]
是的，那个没做更新了，用 github 上的最新版本运行吧，改了不少东西。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: CanisYue <notifications@github.com>
发送时间: 2019年7月22日 21:16
收件人: lmxdawn/vue-admin-html-java <vue-admin-html-java@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[lmxdawn/vue-admin-html-java] 一键下载的百度云失效了 (#1)

**Comment by CanisYue** [comment]
okay
